45 404 page
hlxsites/elco-aerotop-sg pull request #50
Opened 2023-01-26 12:57 UTC by solaris007

Implement 404 page:
- internationalization via placeholders
- styling

Fix #45 

Test URLs:
- Before: https://main--elco-aerotop-sg--hlxsites.hlx.page/de/non-existing-page
- After: https://45-404-page--elco-aerotop-sg--hlxsites.hlx.page/de/nonexisting-page

2023-01-26 13:00 UTC, dzehnder approved these changes, later dismissed
looks good

2023-01-26 13:23 UTC, meryllblanchet requested changes
I observe a flickering, which results in me seeing the message in English briefly before seeing it in the localized version after.
What about not displaying the message in English by default?

Also the page title should be localized, see the <title> tag in the <head> of https://aerotop-sg.com/it/random as an example.

2023-01-27 12:23 UTC, meryllblanchet commented
I added a new entry for the 404 page title localization to the placeholders sheet, with key `errorGeneralPageNotFoundTitle`.

2023-01-30 08:18 UTC, dzehnder approved these changes

2023-01-30 08:31 UTC, merged